Add insert storage
paradigmxyz/pyrevm pull request #23
Opened 2024-10-22 14:35 UTC by replikeit

- Add function that change value in slot by address in database.

2024-10-22 15:11 UTC, SimonOsipov commented
Upvoted 👍

2024-11-01 11:39 UTC, mattsse approved these changes

2024-11-12 18:49 UTC, aymantaybi commented
we need this ASAP

2024-11-12 18:56 UTC, onbjerg requested changes
please fix the failing test

2024-11-12 20:53 UTC, aymantaybi commented
it's just a request rate limitation issue from the rpc provider i guess.

2024-11-12 21:49 UTC, aymantaybi commented
The problem with this feature is that inserting account storage does not override the existing value

2024-11-12 22:21 UTC, aymantaybi commented
================================================================================== test session starts ===================================================================================
platform darwin -- Python 3.12.0, pytest-8.3.3, pluggy-1.5.0
rootdir: /Users/aymantaybi/Documents/GitHub/pyrevm
configfile: pyproject.toml
collected 1 item                                                                                                                                                                         

tests/test_evm.py F                                                                                                                                                                [100%]

======================================================================================== FAILURES ========================================================================================
_________________________________________________________________________________ test_set_into_storage __________________________________________________________________________________

    def test_set_into_storage():
        weth = "0xC02aaA39b223FE8D0A0e5C4F27eAD9083C756Cc2"
        evm = EVM(fork_url=fork_url, fork_block="latest")
        evm.insert_account_storage(weth, 0, 10)
        value = evm.storage(weth, 0)
        assert value == 10
        evm.insert_account_storage(weth, 0, 20)
        value = evm.storage(weth, 0)
>       assert value == 20
E       assert 10 == 20

tests/test_evm.py:71: AssertionError
================================================================================ short test summary info =================================================================================
FAILED tests/test_evm.py::test_set_into_storage - assert 10 == 20
=================================================================================== 1 failed in 0.58s ====================================================================================


I modified the test "test_set_into_storage" to check for overriding the storage IDK if it's an intended behaviour but it's not stated in the underlying implementation.

2024-11-13 14:19 UTC, replikeit commented
Hi, @aymantaybi I fixed your issue in that update, also added tests. Locally all tests have passed.

2025-06-25 12:55 UTC, merged